parameters:
#    melnik_blog.example.class: Melnik\BlogBundle\Example

services:
  melnik_blog.twig.extension:
          class: Melnik\BlogBundle\Twig\Extensions\MelnikBlogExtension
          tags:
              - { name: twig.extension }