parameters:
#    melnik_blog.example.class: Melnik\BlogBundle\Example

services:
#    melnik_blog.example:
#        class: %melnik_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
